apiVersion: apps/v1
kind: Deployment
metadata:
  name: student1-deployment
spec:
  selector:
    matchLabels:
      app: student1
  template:
    metadata:
      labels:
        app: student1
    spec:
      containers:
      - name: student1
        image: registry.tanzu.dk/ops2devops/student1:v1
