apiVersion: apps/v1
kind: Deployment
metadata:
  name: student1-deployment
  namespace: student1
spec:
  selector:
    matchLabels:
      app: student1
  template:
    metadata:
      labels:
        app: student1
    spec:
      containers:
      - name: student1
        image: registry.tanzu.dk/ops2devops/student1:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student1
spec:
  type: NodePort
  selector:
    app: student1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011 # Remember to change to student number.

